### PR TITLE
Update setup.py for installation

### PR DESCRIPTION
**Pull request by heavyimage**
Hello,

I found your dotsecrets repo and it's totally awesome but I had trouble installing it on my machine -- I tweaked the setup.py file (and updated the README) so I can install it on my machine easily.  

Sadly, because I'm new to github, this pull request also includes  a commit where I removed what I think is an errant function from your code -- I can separate that into two pull requests if you prefer.

Thanks for your awesome tool and hope this helps!
Jesse

### CODE REVIEW

**Comment by oohlaf** [comment]
Hi Jesse,

Thank you for your contribution. I'm glad you like it. I'll merge the commits, no need to tweak them into separate merge requests.

The unused function was a leftover from manually testing the code.

Cheers,
Olaf

**Comment by heavyimage** [comment]
Awesome, thanks!  Just out of curiosity -- are you open to more pull requests vis-a-vis documentation or PEP8-ification?  I might hack on it a bit to get my dotfiles setup working perfectly :-)

**Comment by oohlaf** [comment]
Hi, yes I'm open to that. I updated some of the documentation yesterday and fixed the formatting issues on Github.

**Comment by heavyimage** [comment]
Oh whoa!  Nice work.  Thanks for this (sorry if I lit a fire under you to
do this!)

Thanks again for your tool -- maybe now I can get my dotfiles on github :-)

Jesse

On Wed, Jun 29, 2016 at 9:00 AM, Olaf Conradi notifications@github.com
wrote:

> Hi, yes I'm open to that. I updated some of the documentation yesterday
> and fixed the formatting issues on Github.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/oohlaf/dotsecrets/pull/1#issuecomment-229284528, or mute
> the thread
> https://github.com/notifications/unsubscribe/AHdUx19yXyJuyUtRXG77BkorIS9wO0hfks5qQiYKgaJpZM4I-ew3
> .

## 

Jesse Spielman
Compositor / TD / Web Programmer
uk:074.7489.1009
http://www.heavyimage.com

**Pull request merged**
